"""Assemble a Cosmos MAST mission scaffold from a parsed 2.8 mission.

Produces a directory with story.mast, script.py, story.json, description.yaml and
MIGRATION_NOTES.md. The output is a *scaffold*: positions/spawns are real, the rest is
TODO-marked for a human to finish.
"""

from __future__ import annotations

import os
import re

from .emit import Emitter, emit_condition
from .model import Mission
from .parser import parse_file

# Baseline gameplay addons (a gameplay port needs at least consoles); extras are
# feature-detected by the Emitter (e.g. upgrades when anomalies are present).
_BASELINE_ADDONS = ["consoles", "docking", "comms", "damage", "prefabs", "fleets"]
_SBSLIB = "artemis-sbs.sbs_utils.v1.3.0.sbslib"
_ADDON_FMT = "artemis-sbs.LegendaryMissions.{}.v1.3.0.mastlib"


def _slug(name: str) -> str:
    s = re.sub(r"^MISS_", "", name)
    s = re.sub(r"[^A-Za-z0-9]+", "_", s).strip("_").lower()
    return s or "mission"


def _display_name(mission: Mission) -> str:
    return re.sub(r"^MISS_", "", mission.name).replace("_", " ")


def build_story_mast(mission: Mission, em: Emitter) -> str:
    label = _slug(mission.name)
    disp = _display_name(mission)
    lines: list[str] = []
    lines.append(f"# Migrated from {os.path.basename(mission.source_path)} by arme2cosmos.")
    lines.append("# Scaffold only -- see MIGRATION_NOTES.md for the punch-list.")
    lines.append("# Positions use 2.8 coords; a2x_* helpers flip them to Cosmos internally.")
    lines.append("")
    lines.append("PLAYER_CREATE_DEFAULT = False")
    lines.append("")
    lines.append(f'@map/{label} "{disp}"')
    for d in mission.description.replace("^", " ").split("\n"):
        d = d.strip()
        if d:
            lines.append(f'" {d}')
    lines.append("    shared main_story_task = mast_task")
    lines.append("")
    lines.append("    # --- start block ---")
    for n in mission.start:
        lines.append(f"    # {_xml_one(n)}")
        lines.extend(em.emit_command(n))
    lines.append("")

    for i, ev in enumerate(mission.events):
        lines.append(f"--- event_{i}" + (f"   # {ev.name}" if ev.name != f"event_{i}" else ""))
        for c in ev.conditions:
            lines.extend(emit_condition(em, c, i))
        for n in ev.commands:
            lines.append(f"    # {_xml_one(n)}")
            lines.extend(em.emit_command(n))
        lines.append("")

    if not mission.events:
        lines.append("    ->END")
    return "\n".join(lines) + "\n"


def _xml_one(n) -> str:
    attrs = " ".join(f'{k}="{v}"' for k, v in n.attrib.items())
    return f"<{n.tag} {attrs}/>"


def build_script_py(mission: Mission) -> str:
    cls = _slug(mission.name).title().replace("_", "") + "StoryPage"
    return f'''try:
    import sbslibs
    from sbs_utils.handlerhooks import *
    from sbs_utils.gui import Gui
    from sbs_utils.mast.maststorypage import StoryPage
    from sbs_utils.mast.mast import Mast

    class {cls}(StoryPage):
        story_file = "story.mast"

    Mast.include_code = True

    Gui.server_start_page_class({cls})
    Gui.client_start_page_class({cls})
except Exception as e:
    message = e
    def cosmos_event_handler(sim, event):
        import sbs
        sbs.send_gui_clear(event.client_id, "")
        sbs.send_gui_text(event.client_id, "", "text",
                          f"$text:sbs_utils runtime error^{{message}};", 0, 0, 80, 95)
        sbs.send_gui_complete(event.client_id, "")
'''


def build_story_json(em: Emitter) -> str:
    addons = list(dict.fromkeys(_BASELINE_ADDONS + sorted(em.addons)))
    mastlibs = ",\n".join(f'        "{_ADDON_FMT.format(a)}"' for a in addons)
    return ('{\n'
            f'    "sbslib": [\n        "{_SBSLIB}"\n    ],\n'
            f'    "mastlib": [\n{mastlibs}\n    ]\n'
            '}\n')


def build_description_yaml(mission: Mission) -> str:
    disp = _display_name(mission)
    desc = mission.description.replace("^", " ").replace("\n", " ").strip()
    return (f"format version: 1\n"
            f"Category: Standard\n"
            f"Category Priority: C\n"
            f"Visible Mission Name: {disp}\n"
            f"Description: {desc}\n")


def build_notes(mission: Mission, em: Emitter) -> str:
    lines = [f"# Migration notes: {_display_name(mission)}", "",
             f"Source: {mission.source_path}", "",
             "Generated by arme2cosmos. This is a scaffold -- the items below need a human.",
             ""]
    if mission.player_ship_names:
        lines.append(f"Player ship names (2.8): {', '.join(mission.player_ship_names)}")
        lines.append("")
    lines.append("## Punch-list")
    if em.notes:
        # de-dup while preserving order
        for msg in dict.fromkeys(em.notes):
            lines.append(f"- {msg}")
    else:
        lines.append("- (none)")
    lines.append("")
    lines.append("## Reminders")
    lines.append("- Headings from 2.8 `angle` are not yet applied (a2x_angle exists if needed).")
    lines.append("- Ship art is placeholder; resolve via the hull crosswalk (artmap).")
    lines.append("- Events are chained linearly; verify the order matches the original flags.")
    return "\n".join(lines) + "\n"


def convert_file(path: str, out_root: str) -> str:
    """Convert one mission XML; write a scaffold dir under out_root. Returns the dir."""
    mission = parse_file(path)
    em = Emitter(mission)

    story = build_story_mast(mission, em)  # run first so em.addons/notes are populated
    files = {
        "story.mast": story,
        "script.py": build_script_py(mission),
        "story.json": build_story_json(em),
        "description.yaml": build_description_yaml(mission),
        "MIGRATION_NOTES.md": build_notes(mission, em),
    }

    out_dir = os.path.join(out_root, _slug(mission.name))
    os.makedirs(out_dir, exist_ok=True)
    for fname, content in files.items():
        with open(os.path.join(out_dir, fname), "w", encoding="utf-8") as f:
            f.write(content)
    return out_dir
